apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      containers:
      - name: testing
        image: rakeshrampalli/testing:latest
        args:
        - --insecure-skip-tls-verify
        ports:
        - containerPort: 8080
